USSF-ORBIT/ussf-portal-client

.github/workflows/semantic-pr.yml, README.md
Adds a `dev` commit type to our semantic PR config and the README.
Fixes #31 
After merging this, we should be able to open PRs with the title `dev: ...`
=> chore: Add dev commit type

.github/CODEOWNERS
Adding @esacteksab as a default codeowner since having only two owners prohibits us from merging code changes if one is out.
Fixes #53
=> chore: Add Barry as a default codeowner

.github/dependabot.yml
No `package.json` in `/cypress` directory. We don't want to update to Node 16. This should ignore that update.
Fixes #69
=> ci: Updating dependabot. No package.json in /cypress and we don't want Node 16.

cypress/integration/mvp.spec.js, src/__tests__/pages/login-notice.test.tsx, src/pages/login-notice.tsx, src/pages/login/login.module.scss
This PR is based off https://github.com/USSF-ORBIT/ussf-portal-client/pull/103 and adds the Login Notice page (at `/login-notice`).
Fixes #104
You can start the app locally and manually navigate to `/login-notice`. This page should match the same URL on the MVP site.
=> feat: Login Notice page

.github/dependabot.yml, .github/workflows/merge-me.yml
We decided to let Dependabot manage all version updates, even major. But we're configuring `auto-merge` to only manage minor and patch updates. Major updates will still be done manually.
Like the others, this needs to land in `main` to test.
Fixes #111
=> ci: Allow dependabot to manage all version updates, but auto-merge will only automate minor and patch versions.

.github/workflows/node-ci.yml, .gitignore, .storybook/main.js, .storybook/preview.js, package.json, src/components/MVP/Header/Header.stories.tsx, yarn.lock
While working on another issue, I noticed that `yarn storybook` was breaking for a couple of reasons. This PR both:
*  Fixes the Storybook build (by downgrading certain packages that SB is not compatible with yet) and updating the usage of `storybook-addon-next-router`
* Adds a Storybook build to our existing CI so that in the future, changes that break SB will be caught before being merged
This PR does not persist the Storybook output anywhere, but that would be somewhat trivial to do in the future if we want (for example to [Github pages](https://github.com/storybookjs/storybook-deployer))
Fixes #147 
If you look at the [Node CI actions for this branch](https://github.com/USSF-ORBIT/ussf-portal-client/actions/workflows/node-ci.yml?query=branch%3A147-storybook-ci) you can see the …
=> ci: Test Storybook builds during CI

.storybook/preview.js, jest.setup.js, src/components/Bookmark/Bookmark.module.scss, src/components/Bookmark/Bookmark.stories.tsx, src/components/Bookmark/Bookmark.test.tsx, src/components/Bookmark/Bookmark.tsx, src/initIcons.ts, src/pages/_app.tsx, src/styles/_deps.scss
Adds a Bookmark component that wraps the existing `LinkTo` component with some styling and an optional delete button.
Bookmark prop types:
```
type PropTypes = LinkToProps & {
onDelete?: (event: React.MouseEvent<HTMLButtonElement>) => void
}
```
API:
```
<Bookmark href="#">Example</Bookmark>
<Bookmark href="#" onDelete={handleDelete}>Delete Me</Bookmark>
```
Fixes #192 
This PR just adds the new component in Storybook, so to test pull down this branch and run:
```
yarn storybook
```
You should see Bookmark under the Components section in the navigation, and be able to click through the various examples.
One design question for @MKDale @malworks -- I added an example with a long text string, which currently just wraps the text, but another option is to truncate with an ellipsis:
Do you …
=> dev: Bookmark component

src/components/PersonalData/PersonalData.module.scss, src/components/PersonalData/PersonalData.stories.tsx, src/components/PersonalData/PersonalData.test.tsx, src/components/PersonalData/PersonalData.tsx
This PR adds a placeholder component for the greeting/personal data as shown below.
* Static component to use for beta testing more complete pages
* Standard uswds styling
* Adds tests
Fixes #197 
You can view the component in Storybook here: https://197-static-personal-data-component--ussf-storybook.netlify.app/?path=/story/beta-components-personaldata--personal-data-placeholder
=> dev: Placeholder static data component

next-env.d.ts, src/pages/index.tsx
This adds the `usa-link` class to the Quick Links on the home page so they have the correct link color.
Fixes #224 
Bug:
Fixed:
=> fix: Fix link color on home page

cypress/integration/sites-and-applications.spec.js, src/apolloClient.tsx, src/components/Bookmark/Bookmark.module.scss, src/components/Collection/Collection.module.scss, src/components/Collection/Collection.test.tsx, src/components/Collection/Collection.tsx, src/components/CustomCollection/CustomCollection.module.scss, src/components/CustomCollection/CustomCollection.stories.tsx, src/components/CustomCollection/CustomCollection.test.tsx, src/components/CustomCollection/CustomCollection.tsx, src/components/MySpace/MySpace.tsx, src/operations/resolvers.tsx, src/pages/index.tsx, src/pages/login-notice.tsx, src/pages/login/index.tsx, src/pages/training-and-education/force-multiplier-program.tsx, src/styles/mvp/_buttons.scss, src/styles/mvp/_global.scss
This PR adds the "Add link" flow to the Custom Collection component, allowing users to add arbitrary links to existing collections.
In the interest of keeping PRs small, this does _not_ include the modal that asks a user to enter a custom label for their link. That feature is added in https://github.com/USSF-ORBIT/ussf-portal-client/pull/250
I'm considering this branch to be feature complete since a user is still able to add a link. The display text will just default to the URL.
Fixes #233 
* Verify you can click "Add link" on an existing collection in My Space to add a new URL to the collection.
* The text input should validate that you have entered a complete & valid URL. Entering other text or no text at all should prevent you from submitting the link.
* Since the link is only added in …
=> feat: Add custom link to collection

cypress/integration/sites-and-applications.spec.js, src/__tests__/pages/beta/sites-and-applications.test.tsx, src/components/Bookmark/Bookmark.module.scss, src/components/Bookmark/Bookmark.stories.tsx, src/components/Bookmark/Bookmark.test.tsx, src/components/Bookmark/Bookmark.tsx, src/components/CustomCollection/CustomCollection.tsx, src/components/CustomCollection/RemovableBookmark.tsx, src/components/MySpace/MySpace.test.tsx, src/components/SelectableCollection/SelectableCollection.module.scss, src/components/SelectableCollection/SelectableCollection.stories.tsx, src/components/SelectableCollection/SelectableCollection.test.tsx, src/components/SelectableCollection/SelectableCollection.tsx, src/components/modals/AddCustomLinkModal.tsx, src/operations/mutations/addCollections.tsx, src/operations/resolvers.tsx, src/pages/beta/sites-and-applications.tsx, src/styles/pages/sitesAndApplications.module.scss
This PR adds the UX flow to select existing collections from the Sites & Applications page, and add them to a user's My Space. This includes:
*  A "select" state on the Sites & Applications page that renders each collection as selectable buttons, and any links contained within are not clickable.
* A mutation to add multiple collections in a single operation
Fixes #235 
* Even though it wasn't specified in the design, I added an "unselect" handler if you click a collection that has already been selected.
* Since the collections are only stored in the local cache, refreshing the page will reset any changes you've made.
* One thing this PR does _not_ implement is storing references to CMS-managed collections -- it simply copies the data from a collection into a user's customized My Space. …
=> feat: Add existing collections to My Space

cypress/integration/sites-and-applications.spec.js, src/components/CustomCollection/CustomCollection.test.tsx, src/components/CustomCollection/CustomCollection.tsx
This PR adds native form validation to the Add Link input, to verify that when a user is entering a custom link they provide a valid, complete URL. Since this is an initial implementation of this feature, it just uses a regex to verify the input. We may want to use a more robust method in the future since using regex to validate URL strings is usually not recommended.
Fixes #270 
- Go to My Space and click "+ Add link" under a collection
- Try entering a non-URL into the input (i.e., www.example.com). You should see an error message and be prevented from adding the link.
- Verify you can enter a valid URL into the input (i.e., http://www.example.com) and proceed.
- Verify you can also still select an existing CMS link and add it to the collection.
=> feat: Validate custom URL when adding a link to a collection

.github/workflows/dev-aws-ecr.yml, .github/workflows/prototype-aws-ecr.yml
`dev-aws-ecr.yml` will run when merged to main branch. It will get the tag. Log into ECR. Build the image, tag the image based on the git tag and push the image to the Elastic Container Registry in our Dev AWS Account. It will then download the task definition for the dev stack, update it with the image created in the prior step, then update the service with the new image, deploying it. It will then upload the image to C1 Artifactory instance in dev.
`prototype-aws-ecr.yml` is similar to `dev-aws-ecr.yml` but rather than running on merge to main, it will run when a tag of `release-2.0.0-alpha.*` is created. It will not upload to C1 Artifactory. The workflow is otherwise the same in build and deployment deploying to the prototype stack.
Fixes #308
=> ci: Adding AWS Actions

.github/workflows/dev-aws-ecr.yml, .github/workflows/prototype-aws-ecr.yml
The `GHA_ECR` user needs to assume a role. This is supposed to do that.
=> ci: Define the role that the GHA_ECR User should assume

.github/workflows/dev-aws-ecr.yml, .github/workflows/prototype-aws-ecr.yml
When deploying to main, we want to use the git sha, rather than `/main`. For the prototype, we don't want a tag to have `release-` as a part of the name. This does that.
=> ci: use github.sha rather than RELEASE_VERSION when merging to main branch

.github/workflows/dev-aws-ecr.yml
It used to be called `portal-client` but it's now called `portal-client-dev`. This fixes that.
=> ci: Defining the correct task definitiion for dev

.github/workflows/dev-aws-ecr.yml, .github/workflows/prototype-aws-ecr.yml
The container name is actually `portal-client-dev` and `portal-client-prototype`. I tried to change the name in the console and it won't allow it. I think it's created upon creation of the cluster. So I need to update the action to use the properly named container name.
=> ci: tell actions to use the correct container name.

.github/CODEOWNERS
Renovatebot won't automerge because of `CODEOWNERS`, but thanks to a fellow Trussel, and this [link](https://github.com/renovatebot/renovate/issues/6473#issuecomment-855543240), this might do what we want which is make the package files owned by everyone...which says it should allow renovatebot to automerge.
Fixes #
=> ci: Making package files owned by everyone to allow renovatebot to automerge.

.dockerignore, Dockerfile
* Only install production dependencies after building NextJS app
* Use node-slim for final image with deps installed for Prisma
* Ignore `.keystone` directory
=> ci(docker): Reduce size of Docker production image

.github/CODEOWNERS
Adding @noahfirth and @malworks as codeowners while other engineers are out on vacation so we can merge UI work without being blocked.
=> chore: Add Mallory & Noah as temporary codeowners

.github/workflows/dev-aws-ecr.yml
The build process now needs this secret, adding it to the C1 step. I think this will just be the first iteration in getting to push to C1 artifactory. 
Fixes https://github.com/USSF-ORBIT/ussf-portal-client/runs/4369985932?check_suite_focus=true
=> ci: try and fix c1 build error

.github/workflows/dev-aws-ecr.yml
Building for AWS ECR is done _inside_ a Docker container. _This_ step is done inside an Ubuntu runner on Github Actions. So we need to be more explicit for the path of this cert. This does that.
=> ci: C1 doesn't have the Dockerfile COPY step, so we need to be more explicit here

.github/workflows/dev-aws-ecr.yml
Permission denied in the job. This should fix it.
Fixes https://github.com/USSF-ORBIT/ussf-portal-client/runs/4374027106?check_suite_focus=true
=> ci: sudo so we can access /usr/local/share/ca-certificates

.github/workflows/dev-aws-ecr.yml
This repo's actions still continue to fail to talk to artifactory though prototype successfully talks to artifactory with a copy/paste of the action yaml file. All of that to say, this _should_ make Docker aware of the cert chain for artifactory and hopefully appease it.
Fixes https://github.com/USSF-ORBIT/ussf-portal-client/runs/4387505248?check_suite_focus=true
=> ci: Give Docker the cert chain for Artifactory in Dev

.github/workflows/build-push-c1-art.yml, .github/workflows/dev-aws-ecr.yml
[This](https://github.com/USSF-ORBIT/ussf-portal-prototype/runs/4372801956?check_suite_focus=true) works. [This](https://github.com/USSF-ORBIT/ussf-portal-client/runs/4395484444?check_suite_focus=true) continues to fail. At this point, the only difference between the two jobs [1](https://github.com/USSF-ORBIT/ussf-portal-prototype/blob/main/.github/workflows/dev-aws-ecr.yml) [2](https://github.com/USSF-ORBIT/ussf-portal-prototype/blob/barry-test-aws-actions/.github/workflows/dev-aws-ecr.yml) is that the prototype repo doesn't have all the AWS steps prior to C1. So this is me making a unique job for C1 to see if somehow the previous steps are messing things up somehow.
=> ci: Make C1 GHA task it's own job

next.config.js, src/pages/api/graphql.tsx
- Disabled Apollo Server landing page `/api/graphql`
- Turn on React strict mode
Fixes #367 
Fixes #446 
Tests should pass
You shouldn't be able to access the Apollo Server landing page at `/api/graphql`
=> chore: Production readiness

renovate.json
I made some adjustments to Renovate config:
- Turn on the [dependency dashboard](https://docs.renovatebot.com/key-concepts/dashboard/)
- Add presets to group related package updates together
- Added preset to safeguard against npm packages being unpublished
=> ci: Enable dependency dashboard, turn on presets

.storybook/main.js, e2e/cypress/integration/mvp.spec.js, e2e/cypress/integration/news.spec.js, next.config.js, package.json, src/__tests__/pages/beta/news.test.tsx, src/components/BreadcrumbNav/BreadcrumbNav.stories.tsx, src/components/BreadcrumbNav/BreadcrumbNav.test.tsx, src/components/BreadcrumbNav/BreadcrumbNav.tsx, src/components/Header/Header.module.scss, src/components/Header/Header.test.tsx, src/components/Header/Header.tsx, src/components/NewsListItem/NewsListItem.module.scss, src/components/NewsListItem/NewsListItem.stories.tsx, src/components/NewsListItem/NewsListItem.test.tsx, src/components/NewsListItem/NewsListItem.tsx, src/components/PageHeader/PageHeader.module.scss, src/components/PageHeader/PageHeader.stories.tsx, src/components/util/NavLink/NavLink.tsx, src/hooks/useRSSFeed.test.tsx, src/hooks/useRSSFeed.tsx, src/layout/Beta/DefaultLayout/PageLayout.test.tsx, src/layout/Beta/DefaultLayout/PageLayout.tsx, src/pages/beta/news.tsx, src/styles/pages/news.module.scss, src/styles/sfds/index.scss
This PR adds a new page to `/news` which fetches and displays the 12 most recent articles from the SpaceForce.mil RSS feed. A link to the new page is in the header.
It also creates an alternative layout for beta pages that allows passing in a header node, instead of rendering the user's personal data.
New components in Storybook:
* `BreadcrumbNav`
* `NewsListItem`
Fixes #262 
Fixes sc-27
Visit the News page by clicking on the link in the header navigation & verify it loads expected content.
=> feat: News page [sc-27]

package.json, yarn.lock
Updates ReactUSWDS to 2.7.2 to resolve the issue (https://github.com/trussworks/react-uswds/issues/1898)
Fixes sc-224
Start the app and verify that navigating between pages does not add white space to the right side of the window.
=> fix: Modal body padding bug

.github/workflows/codeql-analysis.yml
Advanced Security is free for public repositories, so this is me testing it on a public repo. I want this to exist on our infra repo, but it's private and would cost money. So this lets us evaluate the product and see if we want to pay for it.
Further [details](https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security) about Advanced Security. Eventually, I want to use a tool like [Trivy](https://github.com/marketplace/actions/aqua-security-trivy#using-trivy-with-github-code-scanning) that will allow us to scan our Docker images and then post the results into Github's dashboard. Aquasecurity (the company that makes Trivy) also has some IaC github actions that I want to point at and scan our Terraform.
=> ci: codeql-test

CHANGELOG.md, package.json
* Add/Remove News section on My Space ([#522](https://github.com/USSF-ORBIT/ussf-portal-client/issues/522)) ([d927a1b](https://github.com/USSF-ORBIT/ussf-portal-client/commit/d927a1bad50969c3f302bc18881bd46dd0ae5c31))
* Fix login success redirect status ([#542](https://github.com/USSF-ORBIT/ussf-portal-client/issues/542)) ([17b31ee](https://github.com/USSF-ORBIT/ussf-portal-client/commit/17b31eec6668233977ff728435e67a35b5434577))
=> chore(release): 2.4.0

scripts/deploy-dev-aws.sh
There are two container definitions, the first for `portal-client` the second for `aws-otel-collector`. This change updates the first, but leaves the second alone. This should fix the deploy which breaks as a result of updating both container definitions to use the newly created/uploaded portal-client docker image.
=> ci: Getting first container in the task definition, not all containers.

package.json, yarn.lock
Fixes the error message when trying to access embedded Keystone due to multiple versions of NextJS being installed. Using the resolutions field to force one version of NextJS is preferable to updating Keystone, since we are close to deprecating the embedded version.
---
Verify you can access embedded Keystone admin UI (http://localhost:8000/) and make changes with no errors.
```
yarn install
yarn dev
```
---
=> fix: Force embed keystone to use the same version of NextJS as the app

CHANGELOG.md, package.json
* Migrate 'About us' static content ([#548](https://github.com/USSF-ORBIT/ussf-portal-client/issues/548)) ([979aed5](https://github.com/USSF-ORBIT/ussf-portal-client/commit/979aed5e87d82150f02403a5ac3292c4a4e1f409))
* Remove hardcoded personal info links ([#554](https://github.com/USSF-ORBIT/ussf-portal-client/issues/554)) ([d6ba832](https://github.com/USSF-ORBIT/ussf-portal-client/commit/d6ba832f3527c241bc7ca1e75cceee1067a907ae))
* added IE11 redirect ([#558](https://github.com/USSF-ORBIT/ussf-portal-client/issues/558)) ([2afe71d](https://github.com/USSF-ORBIT/ussf-portal-client/commit/2afe71d34a1b3cb2ee10fec299bb6d4fc66c833c))
* Force embed keystone to use the same version of NextJS as the app ([#557](https://github.com/USSF-ORBIT/ussf-portal-client/issues/557)) …
=> chore(release): 2.5.0

docker-compose.services.yml, docs/development.md
This PR removes Matomo & its database (mariaDB) from the docker compose services stack, since it is not a dependency for running the application and doesn't need to be running during development.
=> chore: Remove Matomo & MariaDB from docker compose services stack

src/components/LoadingWidget/LoadingWidget.module.scss, src/pages/news.tsx
- Adds the LoadingWidget component to the News page
- Updates the LoadingWidget animation to adjust to screen size
---
---
- ... 
---
=> feat: Implement loading state for News page

src/components/Bookmark/Bookmark.module.scss, src/components/CustomCollection/CustomCollection.module.scss, src/components/CustomCollection/CustomCollection.test.tsx, src/components/CustomCollection/CustomCollection.tsx
- Adds cancel button for add link flow
- Updates styling for the CustomCollection and Bookmark components
---
---
- ... 
---
=> feat: Add cancel button to Add Link flow

docker-compose.e2e.yml, docs/development.md, package.json, src/lib/mongodb.ts, startup/index.js, utils/mongodb.js, yarn.lock
Adds a check to the startup script that throws an error if any required environment variables are undefined. Also updates documentation around setting/adding env vars.
To test, edit your local environment to remove some required env vars and try starting the app in dev or production mode:
```
yarn dev
```
```
yarn build && yarn start
```
Instead of starting the app, it should throw an error that includes the name of the env var that is missing.
---
=> ci: Check for required env vars on startup

.envrc, docker-compose.client.yml, docker-compose.e2e.yml, docs/development.md, src/lib/mongodb.ts, startup/index.js, utils/mongodb.js
Fixes an issue introduced in https://github.com/USSF-ORBIT/ussf-portal-client/pull/618 where the environment variables required for connecting to DocDB were removed when they shouldn't have been.
The challenge here is that the connection string for Mongo/DocDB look quite different, and use different env vars. To get around this issue, I am requiring `MONGO_HOST, MONGO_USER, MONGO_PASSWORD` to be defined since those are what are used in deployed environments, but they can be explicitly set to empty strings for local development (which will use `MONGO_URL` instead, as long as its defined).
---
Let's branch deploy to test this on AWS before merging.
=> ci: Fix the environment vars required for Mongo/DocDB

e2e/cypress/integration/sites-and-applications.spec.js, src/operations/queries/getKeystoneBookmarks.tsx
- Fix missing URL descriptions on sites & applications page when sorting alphabetically
- Log in and navigate to the Sites & Apps page
- Click on 'Sort alphabetically' and verify that you can see the description for each url in the list
- Pull down this branch and run locally, while also running the latest version of the CMS
---
=> fix: URL descriptions are not being displayed when sorting sites and applications alphabetically

package.json, yarn.lock
Quite a few vulnerabilities in this repo, but they all seem to relate to `passport-saml-metadata^2.5.0` so I did a [thing](https://github.com/compwright/passport-saml-metadata/pull/35) and it was merged and a tag was cut resulting in [2.6.0](https://github.com/compwright/passport-saml-metadata/releases/tag/v2.6.0) which should address the vulns as a result. Though I am a JS/NodeJS n00b, so I could be completely incorrect.
I did run `yarn test` locally and it appears they all passed.
=> chore(deps): updating passport-saml-metadata to address open vulns

.github/workflows/cypress-ci.yml, .github/workflows/node-ci.yml, .github/workflows/storybook-deploy.yml
When a PR like [this](https://github.com/USSF-ORBIT/ussf-portal-client/pull/651) exists, it doesn't update the github action. This is a known [issue](https://github.com/renovatebot/renovate/issues/7716) and per the workarounds in the [replies](https://github.com/renovatebot/renovate/issues/7716#issuecomment-843239292) this is an attempt to leverage this mechanism. 
The behavior today is to take the PR, manually push to the branch that renovate bot opens, thus tainting the PR so renovate will no longer manage it. This should take the burden off of us needing to update the github action with the proposed nodejs version.
=> ci: use the version defined in package.json, not hardcoded here

docs/development.md
Found that the docs still referred to the use of GitHub Issues and an old version of the branching pattern. This PR updates the docs accordingly.
---
I discovered a test issue getting the project setup, see PR #688 for the fix for that which is part of this one story.
See the modified developer readme.
---
=> docs: update the branch pattern and link to Shortcut

.github/CODEOWNERS
Adding @noahfirth and as a code owner while other engineers are out on vacation so we can merge work without being blocked.
=> chore: add Noah as temporary code owner

src/__tests__/pages/search.test.tsx, src/components/EPubsCard/EPubsCard.module.scss, src/components/EPubsCard/EPubsCard.stories.tsx, src/components/EPubsCard/EPubsCard.test.tsx, src/components/EPubsCard/EPubsCard.tsx, src/pages/search.tsx, src/styles/pages/search.module.scss
Displays an option for the user to search against the e-Pubs site after they perform a search on the portal 
Manually navigate to `http://localhost:3000/search`
- Search for a term (ex: 'pt', 'quill').
- After the search results appear/don't appear, click the 'Seach ePubs' button. A new tab should open and automatically search ePubs using the same query from the portal.
- Also try searching phrases that contain spaces, and see if the ePubs search is consistent.
Make sure you are running the portal client & required services (ie., yarn portal:up in the CMS repo)
---
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.m …
=> feat: ePubs search

package.json, yarn.lock
Tests pass locally and should fix [this](https://github.com/USSF-ORBIT/ussf-portal-client/security/dependabot/10) and [this](https://github.com/USSF-ORBIT/ussf-portal-client/security/dependabot/43).
=> chore(deps): addresses #10 and #43 dependabot alerts

.github/workflows/build-push-c1-art.yml, .github/workflows/codeql-analysis.yml, .github/workflows/cypress-ci.yml, .github/workflows/dev-aws-ecr.yml, .github/workflows/node-ci.yml, .github/workflows/semantic-pr.yml, .github/workflows/storybook-deploy.yml
As discussed in eng sync and similar to https://github.com/USSF-ORBIT/ussf-portal-cms/pull/107 this filters paths so github actions don't always run unnecessarily.
=> ci: filter paths for github actions

.github/settings.yml
Like the PR in the cms repo, this value is unchecked in the UI but also configured here. This is just updating this file to reflect our desired state, to not dismiss stale reviews.
=> chore: disabling the dismissal of stale reviews

CHANGELOG.md, package.json
* Add announcements to news page ([#724](https://github.com/USSF-ORBIT/ussf-portal-client/issues/724)) ([4481828](https://github.com/USSF-ORBIT/ussf-portal-client/commit/44818284934c1aee8e73c3027faa6e13cac3cd90))
* Update URL for News & Announcements and News listing page ([#723](https://github.com/USSF-ORBIT/ussf-portal-client/issues/723)) ([d9fed9e](https://github.com/USSF-ORBIT/ussf-portal-client/commit/d9fed9ea076b1c94508f31c53f7b343c90014b6d))
=> chore(release): 4.6.0

CHANGELOG.md, package.json
* Add internal news carousel for news and announcements page ([#744](https://github.com/USSF-ORBIT/ussf-portal-client/issues/744)) ([c4acfe6](https://github.com/USSF-ORBIT/ussf-portal-client/commit/c4acfe6455f517ce67a8c9fc7639fa0de3c1f7d1)), closes [/github.com/DefinitelyTyped/DefinitelyTyped/issues/35572#issuecomment-498242139](https://github.com/USSF-ORBIT//github.com/DefinitelyTyped/DefinitelyTyped/issues/35572/issues/issuecomment-498242139)
* Display Spaceforce.mil news articles below the news carousel ([#746](https://github.com/USSF-ORBIT/ussf-portal-client/issues/746)) ([e13b57a](https://github.com/USSF-ORBIT/ussf-portal-client/commit/e13b57af70864c1fe1d2774500bb5e077b21cfa0)), closes [/github.com/DefinitelyTyped/DefinitelyTyped/issues/35572#issuecomment-498242139](https://github.com …
=> chore(release): 4.7.0

Dockerfile, next.config.js
- separate single docker `COPY` layer into multiple `COPY` layers so cache is not invalidated on every run
- move docker `BUILD ARG` to end of builder stage and remove `Build Id` from `next build`. Possible future PR to populate `Build Id` in sysinfo at run time
---
To test the docker build, run something like this:
```
docker build . --target=e2e --tag=portal-client:<your-tag-here>
```
I recommend cloning the [e2e repo](https://github.com/USSF-ORBIT/ussf-portal) and running `yarn services:up` from inside the /e2e folder. This will test the Dockerfile changes with `docker compose`.
---
=> ci: optimize docker build cache performance

.github/settings.yml, .github/workflows/node-ci.yml, .happo.js, .storybook/preview.js, docs/development.md, package.json, yarn.lock
As we are working on Dark mode it would be good to know that we haven't broken Light mode version of the portal. To assist in that effort this PR adds Happo configuration to our build pipeline to do testing in chrome, edge, and firefox desktop versions. It also makes the Happo job required.
Looks like my happo runs have a difference, I'm not sure why other than before this I did run the tests from my local machine. I'm leaving them in case folks want to check it out, but I'll likely mark them okay since I didn't change anything that should affect the components that were flagged.
You can see [Happo Docs](https://docs.happo.io/docs) for further details. If you want to run locally you can add the following to your `.envrc.local` 
```sh
export HAPPO_API_KEY=asktalljohnforthis
export …
```
=> ci: Setup happo testing in edge, chrome, and firefox desktop size

src/models/Bookmark.test.ts, src/models/Collection.test.ts, src/models/MySpace.test.ts, src/models/User.test.ts, src/models/User.ts, src/pages/api/graphql.tsx, src/resolvers/index.test.ts, src/resolvers/index.ts, src/types/index.ts
Add `theme` as an attribute of the `User` model. 
I refactored the `User.editOne` to be `User.setDisplayName` as well as added tests for its matching resolver. I did modify it to return data so that the test in the resolver could be written the same way as the others. Please let me know if this breaks something or violates a convention.
I declared `theme` to be of type `'light' | 'dark'` so that auto complete and typescript would know that it should only ever be `light` or `dark`, at least until we add `system` or other themes.
I'm not sure there is a way to try this out yet since there is no graphql setup yet. But sc-1035 is next on my list so that should make it testable.
For now ensure tests pass
```sh
yarn test
```
---
- SC-1035 will add a mutation to GraphQL to set theme, and ensure …
=> feat: update user model for saving dark mode

docs/development.md, src/__fixtures__/newPortalUser.ts, src/operations/portal/mutations/editTheme.graphql, src/operations/portal/queries/getTheme.graphql, src/pages/api/graphql.tsx, src/resolvers/index.test.ts, src/resolvers/index.ts, src/schema.tsx
This work is dependent on PR #772 and story sc-1030 and should be merged AFTER them. It adds the query to return the theme for the current user and the mutation to update the theme. Also modifies the apollo context to set a default theme if one is not present.
Since I was in the file that configures the Apollo server I also [applied their recommendation to bound the cache](https://www.apollographql.com/docs/apollo-server/performance/cache-backends/). As far as I can tell it is already using an internal cache but it is unbounded. Eventually we may want to configure it to use redis. This is for sc-707
This is my first time modifying graphql stuff, please let me know if I missed something or didn't follow a convention I am not aware of.
See the steps in `docs/development.md` to enable the …
=> feat: add mutation for get and set theme

docker-compose.cms.yml, docker-compose.e2e.yml
- extend the connection timeout from CMS App to Keystone DB from the default 5 seconds to 10 seconds
- add a health check to Keystone DB so CMS App waits until it is healthy in Docker Compose
This change only modifies how Docker Compose operates locally. In AWS, the connection string will have to be modified in AWS Systems Manager Parameter Store.
- ...
=> dev: extend connection timeout and add keystone db health check

src/components/AddWidget/AddWidget.module.scss, src/components/NewsListItem/NewsListItem.module.scss, src/components/SelectableCollection/SelectableCollection.module.scss, src/styles/_themes.scss, src/styles/index.scss, src/styles/sfds/index.scss
Adds Dark Mode theme support for:
- News widget on My Space
- Add Section button / section on My Space
- Feedback card in left sidebar on home page
- Selectable collection (when clicking Add section + choose existing > sites and apps > select collection)
You can test by running the portal locally, and also by viewing the following components in Storybook > toggling the theme.
* Sections > everything in this subfolder should display properly
* Feedback Card
To toggle between light and dark mode, open the dev tools in your browser when running the portal, then click Application > Local Storage > Set a key/value pair for theme, dark.
To toggle between light and dark mode in Storybook, click a component/Story, and click the theme toggle in the top toolbar.
- ... 
- Performed [a11y …
=> dev: Dark mode support for My Space and related components

src/components/ArticleList/ArticleList.module.scss, src/components/ArticleList/ArticleList.tsx, src/styles/_themes.scss, src/styles/sfds/_colors.scss
Adds dark mode support for the Pagination component.
---
Since we're waiting for the `Pagination` component to be [merged into ReactUSWDS](https://github.com/trussworks/react-uswds/pull/2188), I thought I should keep the styles separate and NOT create an scss module for the component. With that being said, the only place that the `Pagination` component is currently being used is in the `ArticleList` component, so I added the necessary style updates there. 
Something else to note is that the dark mode toggle in Storybook does not work for `Pagination`. I'm not sure why that is the case, but I was thinking that once the `Pagination` component is merged into ReactUSWDS we'll most likely be removing the component and accompanying storybook stories from this codebase (correct me if I'm wrong …
=> dev: Add dark mode styles for article pagination

CHANGELOG.md, package.json
* add launch darkly flag for dark mode toggle ([#787](https://github.com/USSF-ORBIT/ussf-portal-client/issues/787)) ([397dccd](https://github.com/USSF-ORBIT/ussf-portal-client/commit/397dccddd2fc1475e3638c389d426498dd4080f3))
* save theme setting to database and load theme from database when user logs in ([#778](https://github.com/USSF-ORBIT/ussf-portal-client/issues/778)) ([8a7c8e7](https://github.com/USSF-ORBIT/ussf-portal-client/commit/8a7c8e7e3c272fa5c89ee43e3073af809c8d92de))
* remove unnecessary trailing double quote ([#782](https://github.com/USSF-ORBIT/ussf-portal-client/issues/782)) ([5721bb3](https://github.com/USSF-ORBIT/ussf-portal-client/commit/5721bb3fbf82b6b4d70ec21b69bd10a9cd35dc6e))
=> chore(release): 4.9.0

package.json, yarn.lock
* Adds `trim-newlines` to `resolutions` to resolve dependency issue
* We can't update the parent package, `standard-version`, as it is now deprecated.
I've also created a chore (SC-1232) to migrate off `standard-version` in the future.
To test that releasing still works, you can run `yarn release --dry-run` to see test output without actually creating a new release.
=> chore: Upgrade trim-newlines dependency

package.json, yarn.lock
This deals with [dependabot alert 54](https://github.com/USSF-ORBIT/ussf-portal-client/security/dependabot/54) and [Trivy scan result #89](https://github.com/USSF-ORBIT/ussf-portal-client/security/code-scanning/89)
#845 did not resolve the issue because apollo-server-micro was causing apollo-server-core to resolve to an earlier version. Both packages will be updated to 3.11.1.
Changelog: https://github.com/apollographql/apollo-server/blob/version-3/CHANGELOG.md
=> chore: resolve apollo-server-core@3.11.1

.github/workflows/build-push-c1-art.yml
Add `BUILD` to build-args for deployment image build
This will add the data needed to display `buildId` in `/api/sysinfo` call
Deploy to staging?
=> build: add BUILD to build-args for build

.github/workflows/build-push-c1-art.yml, .github/workflows/node-ci.yml, .github/workflows/storybook-deploy.yml
This replaces the deprecated `set-output` with the new format per the [docs](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
=> chore: replace deprecated set-output in gha

src/components/SingleArticle/SingleArticle.module.scss, src/components/SingleArticle/SingleArticle.stories.tsx, src/components/SingleArticle/SingleArticle.test.tsx, src/components/SingleArticle/SingleArticle.tsx, src/pages/about-us/orbit-blog.tsx, src/pages/news-announcements.tsx, src/styles/pages/news.module.scss
This PR is based on #862 and USSF-ORBIT/ussf-portal-cms#98. It will need to be merged in after both of them.
The aforementioned PRs add support to upload a hero image for an article and return it in the article data. This PR modifies the `SingleArticle` component to display the hero image.
In addition to the css changes needed for the hero image this PR adds a `max-width` attribute to the SingleArticle component and the 2 article lists `orbit blog` and `news and announcements` pages.
Also the labels for an article moved to below the title as in the latest figma design.
I set the `max-width` of the article to `948px` as in figma. That width looked a bit too small for the article lists. I looked in figma and those were wider, so I picked the `1220px` that I found for the `news and …
=> feat: Display hero image in article layout

.github/CODEOWNERS
Also resolves SC-1349
Instead of creating a PR to add or remove code owners this adds a github group to manage the same thing.
I've created PRs for this in the portal (this pr), client (USSF-ORBIT/ussf-portal-client#902), and cms (USSF-ORBIT/ussf-portal-cms#234) repos.
=> build: switch CODEOWNERS to use group code-owners

CHANGELOG.md, package.json
* display hero image in news carousel ([#901](https://github.com/USSF-ORBIT/ussf-portal-client/issues/901)) ([34fefac](https://github.com/USSF-ORBIT/ussf-portal-client/commit/34fefaca76bec59bc9caf707b8878984582680c0))
* **deps:** update dependency micro to v10 ([#879](https://github.com/USSF-ORBIT/ussf-portal-client/issues/879)) ([c538652](https://github.com/USSF-ORBIT/ussf-portal-client/commit/c5386522d8a333dac0f15380f6792cfa62c36eca))
=> chore(release): 4.13.0

CHANGELOG.md, package.json
* Add LaunchDarkly back and put Search behind feature flag ([#912](https://github.com/USSF-ORBIT/ussf-portal-client/issues/912)) ([f235860](https://github.com/USSF-ORBIT/ussf-portal-client/commit/f2358601aa09f8b2c90f8b467821450e305d925c))
=> chore(release): 4.14.0

CHANGELOG.md, package.json
* Connect documents page to cms ([#921](https://github.com/USSF-ORBIT/ussf-portal-client/issues/921)) ([616f5ee](https://github.com/USSF-ORBIT/ussf-portal-client/commit/616f5eee6419820c01016ce5da3cb7221356ab88))
* Display current announcements ([#924](https://github.com/USSF-ORBIT/ussf-portal-client/issues/924)) ([4ad1f8d](https://github.com/USSF-ORBIT/ussf-portal-client/commit/4ad1f8d477f14e59aaa069a1cff882a32b8e459b)), closes [#912](https://github.com/USSF-ORBIT/ussf-portal-client/issues/912) [#925](https://github.com/USSF-ORBIT/ussf-portal-client/issues/925) [#912](https://github.com/USSF-ORBIT/ussf-portal-client/issues/912) [#921](https://github.com/USSF-ORBIT/ussf-portal-client/issues/921)
* Support article scheduling ([#922](https://github.com/USSF-ORBIT/ussf-portal-client/issues/922 …
=> chore(release): 4.15.0

scripts/add-dod-cas.sh
- rename cert which had a spelling mistake
---
---
- ... 
- Run through the [Test Script](hhttps://docs.google.com/spreadsheets/d/1eV8UK0aJZ0qrzjnXf5SJ_uRiV7bpsj3yrhRFEkjOvV4/edit?usp=sharing):
---
=> fix: update dod cas cert name

package.json, yarn.lock
Several package resolutions are unnecessary because either it has been patched by its parent dependency or is a dev-only dependency. 
- `ansi-regex` has been patched to `ansi-regex@5.0.1` in `opentelemetry/exporter-trace-otlp-grpc@0.35.1` and is otherwise a dev-only dependency
- `webpack` is a dev-only dependency
- `parse-url` is a dev-only dependency
- `trim-newlines` is a dev-only dependency
- `trim` is a dev-only dependency
- `glob-parent` is patched to `glob-parent@5.1.2` in `next@12.3.4` and is otherwise a dev-only dependency
---
Run `yarn` to make sure packages are updated locally.
---
Many of these packages are dependencies for Storybook so Storybook should be checked.
=> chore(deps): remove unnecessary resolutions

CHANGELOG.md, package.json
* Display video in an article ([#923](https://github.com/USSF-ORBIT/ussf-portal-client/issues/923)) ([d1a0797](https://github.com/USSF-ORBIT/ussf-portal-client/commit/d1a0797e46d50f34d10157d85982991785abd11b)), closes [#941](https://github.com/USSF-ORBIT/ussf-portal-client/issues/941)
* Guardian Ideal carousel ([#938](https://github.com/USSF-ORBIT/ussf-portal-client/issues/938)) ([aa645da](https://github.com/USSF-ORBIT/ussf-portal-client/commit/aa645da5dd4ef9476ef0cabe7e8e50bc4f1691d9))
* update dod cas cert name ([#950](https://github.com/USSF-ORBIT/ussf-portal-client/issues/950)) ([119a3b6](https://github.com/USSF-ORBIT/ussf-portal-client/commit/119a3b680346267df1beab238e60be93474ef48d))
=> chore(release): 4.16.0

.github/workflows/storybook-deploy.yml
To allow testing of workflow changes via `gh` cli enable workflow trigger for storybook deploy workflow.
None, once merged we will be able to trigger the flow manually
=> ci: allow storybook deploy workflow be manually triggered

src/components/FeaturedShortcuts/FeaturedShortcuts.module.scss, src/components/FeaturedShortcuts/FeaturedShortcuts.stories.tsx, src/styles/_themes.scss
This branch adds in featued shortcuts component to stroybook and also does dark mode styling, adds in theme variables for featured shortcut items
```sh
yarn storybook
```
[http://localhost:6006/?path=/story/components-widgets-featuredshortcuts--featured-shorcuts-widget](http://localhost:6006/?path=/story/components-widgets-featuredshortcuts--featured-shorcuts-widget )
---
- ... 
- Run through the [Test …
=> feat: design: storybook: adds featured shortcuts to storybook and styles for dark mode

src/components/FeaturedShortcuts/FeaturedShorcuts.tsx, src/components/FeaturedShortcuts/FeaturedShortcuts.test.tsx, src/stores/analyticsContext.tsx, src/types/index.ts
Adds additional event tracking for when a user clicks on a featured shortcut
---
A couple of ways to test:
- Run the app locally, click a featured shortcut, and check your browser console to see if the event fired
- Push this branch to the dev environment, login to Matomo on dev, and verify that the events fire as expected
Run the client as usual. The CMS can run on main:
- In the CMS repo `yarn services:up && yarn dev`
- In the portal `yarn dev`
---
- ... 
- Performed [a11y …
=> dev: Additional event tracking for featured shortcuts

src/components/NewsItem/NewsItem.module.scss, src/components/NewsItem/NewsItem.tsx, src/stories/type.stories.tsx, src/styles/_govBanner.scss, src/styles/_themes.scss, src/styles/sfds/index.scss
This branch adjusts the dark background base link styles and ensures it is [displayed correctly in storybook](http://localhost:6006/?path=/story/global-typography--links). 
This branch also adjusts link colors that were catching color contrast violations on a few components including:
- the [logout button](http://localhost:6006/?path=/story/navigation-header--default-header) (this also aligns it to what we have in figma) -> text changed from white to black
- the [news item tag ](http://localhost:6006/?path=/story/components-newswidget-newsitem--rss-article)(i know its design is going to change but in the meantime i aligned it more to what its changing to) -> text color darkened and background lightened
- the 'Here's how you know' link in the gov banner. this actually turned out to be …
=> fix: design: storybook: link color adjustments and storybook documentation

migrations/1679951734168-add-featured-shortcuts-widget.js, src/types/index.ts, test/migrations/add-featured-shortcuts-widget.test.js
* New migration to add FeaturedShortcuts widget to users' MySpace
* If the user already has the FeaturedShortcuts widget, no action will be taken
* Down migration will only remove FeaturedShortcuts widget added by the migration. Users who added it previously should not be affected.
* To differentiate between users who already have the Featured Shortcuts widget in their MySpace, and users who will receive the update, I added the field `default: true` to the widget.
* Happo diffs seem to be known issue with YouTube thumbnails, but tagging design for review anyway
You can test the migration locally in two ways:
1. Start the services with `yarn services:up`.  View the mongodb users via `localhost:8888` and verify there is an existing user. If you've recently purged your local db, log in as …
=> chore: Add migration for featured shortcuts default widget

migrations/1680214667334-remove-null-bookmarks.js, src/operations/portal/mutations/editCollection.graphql, src/schema.tsx, test/migrations/remove-null-bookmarks.test.js
Somehow a user has a collection with a bookmark of value `null`. This PR changes our graphql schema to require bookmark objects in the collections objects to prevent this from happening again. It also introduces a migration that removes any null bookmark records from all users.
Collection schema was changed so try as many collection actions as you can. If you want to test the migration use mongo express to add null as a record in bookmark then run the migration
To clear db of nulls
```
yarn migrate up 1680214667334-remove-null-bookmarks.js
```
To reset migration - does nothing to the data
```sh
yarn migrate down 1680214667334-remove-null-bookmarks.js
```
Standard startup 
```sh
cd ../cms && yarn dev
cd ../client && yarn dev
```
=> fix: Remove any null bookmarks and prevent future ones

src/styles/pages/settings.module.scss
Adds background fill css to the widget box container surrounding the box on the settings page
sets text fields in light mode to default to white to account for layouts like this, they were transparent before, and we dont want text fields to become illegible if they are on an unexpected background in the future.
```
yarn dev
```
http://localhost:3000/settings
---
=> fix: design: adds background fill settings box 

.github/workflows/node-ci.yml
To better support experimenting with our workflow adding a manual trigger to node-ci workflow file. I want to see if we can save the storybook artifact built by happo testing process to reuse when deploying storybook.
=> ci: allow ci build node-ci to be triggered manually

.github/CODEOWNERS, .github/settings.yml, .github/workflows/storybook-deploy.yml, .storybook/main.js, .storybook/preview.js, CNAME, package.json, yarn.lock
Storybook is deployed to github pages but has been failing to properly host assets. Turns out the module we use to [deploy storybook](https://github.com/storybookjs/storybook-deployer) was deprecated Jan 16, 2023. In case the original url stops working it redirects [here](https://github.com/storybook-eol/storybook-deployer). This PR updates the work flow to use a new Github action based deployer. [Deploy React to Github Pages action](https://github.com/marketplace/actions/deploy-react-to-github-pages) which relies on [GitHub actions deploy beta](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/) that came out Jul 27, 2022. 
Another option is [Deploy to Github pages](https://github.com/marketplace/actions/deploy-to-github-pages) action as well. The …
=> build: switch storybook deploy action

CHANGELOG.md, package.json
* design: adds background fill settings box  ([#973](https://github.com/USSF-ORBIT/ussf-portal-client/issues/973)) ([d63c948](https://github.com/USSF-ORBIT/ussf-portal-client/commit/d63c94802bc81425c9664f6006a50e8067d88851))
* design: sets Trebuchet as default font for all USWDS components ([#971](https://github.com/USSF-ORBIT/ussf-portal-client/issues/971)) ([3654c05](https://github.com/USSF-ORBIT/ussf-portal-client/commit/3654c05b933a8aec87fd06f3ae54bea4e38c6973))
=> chore(release): 4.18.1

.github/workflows/build-push-c1-art.yml, .github/workflows/dev-aws-ecr.yml, Dockerfile, scripts/add-dod-cas.sh, scripts/create-gcds-chain.sh
- added a checksum file for Certs in DoD PKI CA Cert bundle from GH Secrets
- modfiy `add-dod-cas.sh` to download Cert bundle without strict TLS verification
- modify `add-dod.cas.sh` to verify the sha256 checksum of the certs that are downloaded against the checksum file to deter MITM attacks
---
The workflow `.github/workflows/build-push-c1-art.yml` was tested with a manual dispatch and the results can be seen here: https://github.com/USSF-ORBIT/ussf-portal-client/actions/runs/4724289278
The output of the `Add DoD Certifaction Bundle` should include this:
```
Verification successful
certificates_pkcs7_v5_11_dod_der.p7b: OK certificates_pkcs7_v5_11_dod_dod_root_ca_3_der.p7b: OK certificates_pkcs7_v5_11_dod_dod_root_ca_4_der.p7b: OK certificates_pkcs7_v5_11_dod_dod_root_ca_5_der.p7b: OK …
```
=> build: download ca bundle without strict cert check and verify sha256 sum

renovate.json
- CMS and ussf-portal already have these changes which will make Renovate Bot work in way that's easier for humans to interact with.
- Dependencies will be groups in ways that make logical sense so that more PRs are automatically passing checks without needing human intervention
- Lock File Maintenance is enabled so that downstream dependencies also are updated on a regular cadence.
=> chore: carry over cms renovate changes to client

CHANGELOG.md, package.json
* Add hover states to bookmarks ([#987](https://github.com/USSF-ORBIT/ussf-portal-client/issues/987)) ([2dc25db](https://github.com/USSF-ORBIT/ussf-portal-client/commit/2dc25dbe7d2e5a1e2e6c4dfa0b33cd7337276cba))
* Add migration for default Guardian Ideal widget ([#977](https://github.com/USSF-ORBIT/ussf-portal-client/issues/977)) ([ce0eb97](https://github.com/USSF-ORBIT/ussf-portal-client/commit/ce0eb9767ef7210789e4715d7942eb86d7d41be1))
* Clickable tags and labels on Single Article ([#997](https://github.com/USSF-ORBIT/ussf-portal-client/issues/997)) ([9438fc6](https://github.com/USSF-ORBIT/ussf-portal-client/commit/9438fc6c98619069204ca3216337456a1e2b02c4))
* design: On error pages (and elsewhere) offer a bug report page ([#983](https://github.com/USSF-ORBIT/ussf-portal-client/issues/983 …
=> chore(release): 4.19.0

src/__tests__/pages/sites-and-applications.test.tsx, src/components/AddWidget/AddWidget.stories.tsx, src/components/AddWidget/AddWidget.test.tsx, src/components/AddWidget/AddWidget.tsx, src/components/CustomModal/CustomModal.stories.tsx, src/components/FeaturedShortcuts/FeaturedShorcuts.tsx, src/components/FeaturedShortcuts/FeaturedShortcuts.test.tsx, src/components/GuardianIdeal/GuardianIdealCarousel.test.tsx, src/components/GuardianIdeal/GuardianIdealCarousel.tsx, src/components/MySpace/MySpace.test.tsx, src/components/NewsWidget/NewsWidget.stories.tsx, src/components/NewsWidget/NewsWidget.test.tsx, src/components/NewsWidget/NewsWidget.tsx, src/components/Widget/Widget.stories.tsx, src/components/Widget/Widget.test.tsx, src/components/Widget/Widget.tsx, src/models/MySpace.test.ts, src/models/MySpace.ts, src/pages/sites-and-applications.tsx, src/stores/modalContext.test.tsx, src/stores/modalContext.tsx, src/stories/type.stories.tsx
- Add Section now reads Add widget
- Add News Section now reads Add News widget
- Add Featured Shortcuts Section now reads Add Featured Shortcuts widget
- Add Guardian Ideal Section now reads Add Guardian Ideal widget
- Update variable names that use 'section' to use 'widget'
- Update modals to use the word 'widget'
---
Run the app locally:
- Add/remove widgets from MySpace. All references of 'section' should now be 'widget'
- Check out the e2e tests: https://github.com/USSF-ORBIT/ussf-portal/pull/267
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
Check out our [How to review a pull …
=> refactor: Update Add Section labels

.github/workflows/release-please.yml
Add a workflow to automate release PR creation with [release-please GH action](https://github.com/google-github-actions/release-please-action). I left standard-version in the `package.json` and the release instructions as I'd like to see how this works first.
Probably nothing to do until this is merged and we use it for our next release.
=> build: add release-please to the project

.eslintrc.json, src/components/Tag/Tag.tsx, startup/logging.js
This has been on my mind for a while. I made `security/detect-object-injection` as error level lint issues. This will break the build if you add any. This PR fixes a couple issues and marks the rest as accepted exceptions to that.  This PR also disabled `no-console` as a warning since we use `console` messages for server side logging. See https://eslint.org/docs/latest/rules/no-console
I am doing this because it is easy to ignore warnings and I wanted to help reduce that concern and allow us to document when we add exceptions to that. 
This is a proposal and not necessarily how we need to do things so feel free to push back on making the two lint checks error level vs warning level.
Review the fixes and any comments disabling specific lines for accuracy and clarity.
NOTE: ADR proposed for …
=> dev: error on detect-object-injection

src/__tests__/pages/404.test.tsx, src/__tests__/pages/500.test.tsx, src/__tests__/pages/_error.test.tsx, src/pages/404.tsx, src/pages/500.tsx, src/pages/_error.tsx
Add event tracking to 404 and 500 pages
---
Check the console in your browser and you should see a `trackEvent` log when visiting either the `/404` or `/500` pages. You could also try looking at the local instance of Matomo at `https://localhost:8443` but I'm not sure how long it takes for user events to pop up there.
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> feat: Add event tracking to 404/500 error pages

scripts/add-dod-cas.sh
Proposed changes
- The latest DoD PKI CA Certificates Bundle (PKCS#7) v5.12 has been released.](https://cyber.mil/announcement/new-dod-pki-cas-released/) and needs to be updated in our Docker build.
- The GH secret containing the sha256 hashes of the Bundle also has to be updated.
- Removed `--no-check-certificate` from wget command because the DoD PKI portal is no longer failing TLS check.
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> build: update DoD PKI Bundle to v5.12

.github/settings.yml
Update the team names in `.github/settings.yml` to see if that corrects the configuration issue.
=> build: fix the team names

.github/settings.yml
- Update the team names in .github/settings.yml to not have `org` name to see if that corrects the configuration issue.
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> build: allow design, eng, and owners merge to main 2

.eslintrc.json, src/apolloClient.tsx, src/components/DropdownFilter/DropdownFilter.stories.tsx, src/lib/keystoneClient.ts, src/lib/redis.ts, src/lib/requireAuth.ts, src/lib/saml.ts, src/lib/session.ts, src/models/Bookmark.ts, src/models/Collection.ts, src/models/MySpace.ts, src/pages/api/auth/[[...action]].ts, src/stores/analyticsContext.tsx, src/stores/authContext.tsx, src/stores/launchDarklyContext.tsx, startup/logging.js, startup/migrate.js, utils/mongodb.js
In accordance with [ADR 0021](https://github.com/USSF-ORBIT/ussf-portal/blob/main/docs/adr/0021-disable-no-console-eslint-warning.md) this PR makes `console.log` a lint error but allows the other `console.*` methods. This PR also fixes the few legitimate uses of `console.log` with a more specific method like `console.warn` or `console.info`
I left `console.debug` because I found one case where inside a `if (debug === true)` check we had a console log call and debug seemed the most appropriate method to use there.
Run `yarn lint` with no errors and ensure system still works as expected
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
Login to storybook http://localhost:6006, though the command above should …
=> build: error on no-console unless approved method

renovate.json
- Several `@opentelemetry` are used in our package.json. These should have their own group in Renovate so they can be updated together. This should make the `renovate/dependencies` branch less crowded too
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> chore: add otel package rule to renovate config

src/__fixtures__/data/cmsAnnouncments.ts, src/__tests__/pages/article.test.tsx, src/components/AnnouncementInfo/AnnouncementInfo.test.tsx, src/components/AnnouncementInfo/AnnouncementInfo.tsx, src/pages/articles/[article].tsx
And SC-2010
This PR fixes it so that announcements with a CTA button to a deleted article does not cause a 500 error. The button will send the user to a 404 page. SC-2007
This PR also fixes it so that when a CMS user goes to an article page that doesn't exist it does not cause a 500 error. It will now properly return a 404. SC-2010
I did have to refactor the unit tests for the article page, as one of the tests would have caught the cms user 500 error if the mock had been properly setup.
For SC-2007 Create a published article. Then create an announcement with a CTA button that points to that article. Finally delete the article and visit the landing page. The Announcement should show up, and the button will take you to the 404 page.
For SC-2010 Go to any article page that doesn't exist …
=> fix: handle removed articles linked in announcements and missing articles for cms users

src/components/CustomCollection/CustomCollection.tsx, src/components/MySpace/MySpace.tsx, src/hooks/useCloseWhenClickedOutside.ts
In https://github.com/USSF-ORBIT/ussf-portal-client/pull/1056 we added the ability to drag and drop collections. We have discovered that when a user drags and drops a collection and then edits that collection, the collection moves back to where it was in the user's My Space originally. 
This fix simply removes the `optimisticResponse` and `update` options that were being passed to `handleEditCollection` and adds `refetchQueries[getUser]` to properly update the `MySpace` component after the drag and drop operation.
To do:
- ~Add e2e tests~
---
Here are the e2e tests: https://github.com/USSF-ORBIT/ussf-portal/pull/302
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
Login to storybook http://localhost:6006, …
=> fix: Fix drag-and-drop bug

src/__fixtures__/data/hourlyForecast.ts, src/__tests__/pages/index.test.tsx, src/components/MySpace/MySpace.test.tsx, src/components/MySpace/MySpace.tsx, src/components/WeatherWidget/WeatherWidget.test.tsx, src/components/WeatherWidget/WeatherWidget.tsx, src/hooks/useWeather.tsx, src/pages/api/dataSources/personnel.ts, src/stores/authContext.test.tsx, src/stores/authContext.tsx
Adds tracking to the 'Retry' button in the WeatherWidget component, so that we can track how many requests to the NWS API fail, and how often the user has to retry the request.
---
IMPORTANT: If you have been reviewing another Matomo-related PR, be sure to destroy all of your containers, and do a fresh build.
Testing this is going to be a bit tricky. Here are the steps:
- Login to the portal and create a weather widget
- Go to `localhost:8888` and find your user in the dev db
- Edit the `hourlyForecastUrl` field on the weather widget to be an invalid url. This will cause the weather widget in the user's My Space to have an error, causing the `Retry` button to appear.
- Go back to `localhost:3000` and click the `Retry` button
- Go to `localhost:8081` in order to look at Matomo. Make sure …
=> dev: Add tracking for retrying the weather request

.storybook/main.js, src/components/Loader/Loader.tsx, src/components/WeatherWidget/WeatherWidget.test.tsx, src/components/WeatherWidget/WeatherWidget.tsx
The weather widget was using the current date for displaying the month and day in the weather widget. This PR changes it to use the date in the forecast response. Also this PR changes the unit test to mock the call to the api.
Also this PR uses the special attribute `data-happo-hide` on the star field in the loader as described in the [happo docs on spurious diffs](https://docs.happo.io/docs/spurious-diffs) to hide the star field from happo. The star field is randomly generated each build so it will always be different in each build.
The fixtures used have a hard coded date of Aug 16th, 2023 which was a Wednesday. This is reflected in the unit test conditions I added and in the storybook renderings, see screenshot below.
```sh
yarn dev
yarn dev
``` …
=> fix: use date from api for weather widget

src/components/ArticleListItem/ArticleListItem.module.scss, src/components/ArticleListItem/ArticleListItem.test.tsx, src/components/ArticleListItem/ArticleListItem.tsx, src/components/SearchResultItem/SearchResultItem.module.scss, src/components/SearchResultItem/SearchResultItem.test.tsx, src/components/SearchResultItem/SearchResultItem.tsx
This branch removes the string output of a raw link url from the search results and article list items. The header 3 is already linked, and in usability testing with screen reader users, the additional link named with the URL made for a painful experience navigating search results and articles. 
When the link is removed, it causes the paragraph element in the result to come very close to the h3. This branch also adds 8px of margin under the h3 to account for this, and ensures the spacing is consistent across both components.
```sh
yarn dev
yarn dev
```
http://localhost:3000/news-announcements
or search something
```sh
yarn storybook
```
Login to storybook http://localhost:6006, though the command above should …
=> fix: a11y: removes raw link output from search results

src/__tests__/pages/404.test.tsx, src/__tests__/pages/500.test.tsx, src/__tests__/pages/_error.test.tsx, src/components/FeaturedShortcuts/FeaturedShortcuts.test.tsx, src/components/FeedbackCard/FeedbackCard.test.tsx, src/components/GuardianIdeal/GuardianIdealCarousel.test.tsx, src/components/MySpace/MySpace.tsx, src/components/ThemeToggle/ThemeToggle.test.tsx, src/stores/analyticsContext.test.tsx, src/stores/analyticsContext.tsx
Add custom dimension to Matomo to track base location
TO DO:
- ~Add tests~
---
Testing this will require a small amount of setup. Here is what you need to do:
- Once you have all services running, navigate to `http://localhost:8081` (Matomo)
- Click the cog icon in the top right 
- You should now be on the Administration page. Look at the left menu, click Websites and then Custom Dimensions 
- You should see something that looks like this, although you shouldn't see CustomLocation yet. Click the big green button to create a new dimension. Make sure you are under VISIT DIMENSIONS 
- Now create a custom dimension. I called mine CustomLocation because a Locations dimension already exists by default in Matomo (and just in case you're wondering, I did try to override it, but the docs advise …
=> dev: Track base location

src/pages/api/dataSources/weather.ts
To support mocking out the weather API in our E2E tests this PR sets it up so that the weather api endpoint can be over ridden by an environment variable. I didn't want to require adding this to each of our environments right away, especially since it is only needed for the E2E tests. We can switch to only the environment var in the future after this and remove the conditional and add the new var to the list in `startup/index.js` file.
If you want to use the mocked service locally add the following to your `.envrc.local`. 
```sh
export WEATHER_API_URL=https://nws-ussf-e2e.wiremockapi.cloud/points/
```
⚠️ **NOTE** if you do this only the following zip codes are setup (aka stubbed) in the mock api. (90210, 85202, 85001, 30310, and 60601)
See also …
=> build: allow env var override the weather api endpoint

src/styles/_colors.scss, src/styles/_themes.scss, src/styles/sfds/index.scss
- changes log out button to have same color in both themes instead of slightly shifting color
- adds ussf blue to box next to active link in `PageNav` to replace uswds default
- removes unused light blue color from colors variables scss file
- changes menu button to use ussf blue instead of uswds default
- see PageNav in My Space page - box next to active link should match link text color
- switch between dark mode and light mode, see there is no color change in the log out button background
- shrink screen size and see menu button matches other button styles more closely
```sh
yarn storybook
```
**Storybook not running locally for me.. direct links to …
=> fix: design: misc color adjustments in links & buttons

src/helpers/openDocumentLink.ts, src/models/MySpace.test.ts
* Changes `endsWith` to `includes` when checking an asset url for the `pdf` extension
* Adds a unit test to bump coverage
PDFs will now open in-browser. Other document formats will continue to download to a user's machine.
In addition to the small code change, we need to update the CORS settings on the s3 bucket. This change has been made on dev, so the feature should now work as expected on dev.ussforbit.us. @jbecker01 Let me know when you're ready to test and I can double check that the branch is available on dev!
When we're ready to deploy, we'll also need @minhlai's assistance to make the changes on staging and prod.
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
Login to storybook …
=> fix: Open document in browser

.github/workflows/release-please.yml
- Now that we have created a GH machine user and a Personal Access Token for Release-Please, we have to instruct the reusable workflow caller to allow the called release-please workflow to inherit secrets from the caller. This will give the reusable Release Please workflow the access to the PAT.
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> ci: allow release please reusable workflow to use org secrets

src/pages/landing/[landingPage]/[article]/index.tsx
More consistent breadcrumbs for articles that are nested under a landing page
---
After https://github.com/USSF-ORBIT/ussf-portal-client/pull/1153 merged, I noticed that the breadcrumbs for an article would default to title case, and I don't think we want that for acronyms. An article with the path `http://localhost:3000/landing/cso/article-two` looked like this:
This is what it looks like now:
And this is what it looks like with a path that contains hyphens. The path `http://localhost:3000/landing/deputy-chief-of-space/test-page` looks like this:
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
Check out our …
=> feat: Update breadcrumb display for articles

renovate.json
- Add `@storybook`  PackageRule for grouping Storybook updates
- Update `description` config option in PackageRules to be arrays of strings instead of strings
- Update `manager` config option to be `matchManagers`
Changes fix these validation errors that must have appeared when Renovate had updates that we didn't keep up with:
```json
DEBUG: Validation Errors
{
"errors": "Configuration option `packageRules[1].description` should be a list (Array), Configuration option `packageRules[2].description` should be a list (Array), Configuration option `packageRules[3].description` should be a list (Array), Configuration option `packageRules[4].description` should be a list (Array), Configuration option `packageRules[7].description` should be a list (Array), Configuration option …
```
=> chore(deps): group renovate storybook updates and fix validation errors

src/__tests__/pages/api/auth/[[...action]].test.ts, src/__tests__/pages/redirect.test.tsx, src/components/Redirect/Redirect.stories.tsx, src/components/Redirect/Redirect.test.tsx, src/components/Redirect/Redirect.tsx, src/helpers/index.test.ts, src/helpers/index.ts, src/pages/api/auth/[[...action]].ts, src/pages/redirect.tsx
This PR fixes the redirect process for when a user tries to go to the CMS first. This was introduced in https://github.com/USSF-ORBIT/ussf-portal-client/pull/1144. The change adds a redirect page that users are temporarily sent to in the portal which then redirects them to the cms after 5 seconds. The page also displays the link that the user is going to be redirected to in case the automatic one doesn't work.
---
Go to http://localhost:3001 and you should be redirected to the login flow and end on the cms page.
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
Check out our [How to review a pull …
=> fix: redirect to cms on login

renovate.json
- This should fix the issue with storybook packages not matching the `@storybook` prefix
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> chore(deps): renovate include storybook prefix and suffix pattern

src/__fixtures__/authUsers.ts, src/models/User.test.ts, src/models/User.ts, src/pages/api/graphql.tsx, src/types/index.ts
This PR adds a new field to the mongo user data called `lastLoginAt`. It is the date of the last login of a user stored as an ISO formatted string. This field is updated every time a user visits a page in the portal. As noted in the story we want to track the data in case we ever run into the duplicate user issue or if we decided to look at number of users active in some period of time.
---
This change is only in the back end. So the data will only be saved in Mongo but not displayed anywhere. Locally you can use Mongo Express to view it by going to http://localhost:8888/db/dev/users and viewing the user data.
```sh
yarn dev
yarn dev
```
Then view http://localhost:8888/db/dev/users to see that your record now …
=> feat: add lastLoginAt to user

src/pages/guardian-directory.tsx
Add the LoadingWidget to the Guardian Directory
---
Navigate to `http://localhost:3000/guardian-directory`
When running this locally, you probably won't see the loading state because of how few test fields there are. You can do one of two things:
- You can download the full spreadsheets from the GDrive, add them to your local ussf-personnel-api and update the docker-compose.services.yml file in this repo to point to your local personnel api.
- Or you can simply go to `src/pages/guardian-directory.tsx` and change `!directory.length` on line 86 to `true`. Save and reload the app to see the loading state.
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
Login to storybook http://localhost:6006, though the …
=> feat: Add LoadingWidget to Guardian Directory page

src/__fixtures__/data/cmsSearch.ts, src/__fixtures__/data/searchResults.ts, src/__tests__/pages/search.test.tsx, src/components/SearchResultItem/SearchResultItem.stories.tsx, src/components/SearchResultItem/SearchResultItem.test.tsx, src/components/SearchResultItem/SearchResultItem.tsx, src/constants/index.ts, src/helpers/index.test.ts, src/helpers/index.ts, src/operations/cms/queries/getLandingPage.ts, src/pages/landing/[landingPage]/index.tsx, src/pages/search.tsx, src/stories/searchresults.stories.tsx, src/types/index.ts
- CMS returns article permalinks in search result query so we don't need to calculate it anymore
---
- https://github.com/USSF-ORBIT/ussf-portal/pull/353
- https://github.com/USSF-ORBIT/ussf-portal-cms/pull/418
- Create a published landing page
- Search by content in description, title, or slug
- Search by using tag short cut `tag:landing-page-tag` or `tag:"beatae quis vel"` if it has spaces.
- Draft landing pages, or pages published in the future will not show up
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
Check out our [How to review a pull request](https://github.com/USSF-ORBIT/ussf-portal/blob/main/docs/h …
=> feat: add landing pages to search results

src/pages/guardian-directory.tsx
- adds label attribute to search guardian directory search field to provide an accessible name that provides sufficient context
- related: [new issue in react-uswds](https://github.com/trussworks/react-uswds/issues/2736) to provide accessible name to small search component
```sh
yarn dev
yarn dev
```
http://localhost:3000/guardian-directory
---
=> fix: a11y:  Guardian Directory field labeling

src/__tests__/pages/settings.test.tsx, src/components/EditDisplayName/EditDisplayName.test.tsx, src/components/EditDisplayName/EditDisplayName.tsx
- remove h3 from the Edit Display Name component, it breaks the heading order and the sequence was weird
- `Update name` label should be `update display name`
- `New display name has been saved` instead of `new title has been saved` in success message
- add `required` attribute to update display name, move asterisk to after the label, corrects `id`/`htmlFor` name connection between the `label` and `input`
`yarn storybook`
http://localhost:6006/?path=/story/components-editdisplayname--default-edit-display-name
http://localhost:3000/settings
---
=> fix: a11y: edit display name component syntax 

.envrc, docker-compose.services.yml, src/pages/api/thirdparty/dataSources/thirdPartyKeystone.ts, src/pages/api/thirdparty/operations/getDocuments.ts, src/pages/api/thirdparty/operations/getInternalNewsArticles.ts, src/pages/api/thirdparty/operations/getLandingPageArticles.ts, src/pages/api/thirdparty/operations/getNewsArticles.ts, src/pages/api/thirdparty/resolvers.test.ts, src/pages/api/thirdparty/resolvers.ts, src/pages/api/thirdparty/schema.ts
- Add CMS Documents to third-party API for authenticated users
- Add InternalNews and LandingPage articles to third-party API for authenticated users
---
You will need to create some articles on your local machine with the categories `InternalNews` and `LandingPage`
You will also need to follow the instructions for [generating a JWT](https://github.com/USSF-ORBIT/ussf-portal/blob/main/docs/how-to/generate-jwt-token.md)
- I've update the Postman collection and posted it in Slack
- After generating your token, you will find the new endpoints under `USSF Third Party API` > `Auth` in the Postman collection
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
Login to storybook http://localhost:6006, though the …
=> feat: Add additional content to third-party API

src/__tests__/pages/search.test.tsx, src/components/AddWidget/AddWidget.test.tsx, src/components/AddWidget/AddWidget.tsx, src/components/MySpace/MySpace.tsx, src/components/PageNav/PageNav.test.tsx, src/components/PageNav/PageNav.tsx, src/components/util/DraggableWidget/DraggableWidget.tsx, src/pages/guardian-directory.tsx, src/pages/search.tsx, src/stores/launchDarklyLocal.ts
Remove LaunchDarkly flags from features we are not going to turn off. Everything should still work the same.
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> chore: review launchdarkly flags

src/__tests__/pages/guardian-directory.test.tsx, src/pages/guardian-directory.tsx
this branch adds a page title attribute to the Guardian Directory page, ensuring it has a unique page title that explains its purpose. This ensures the page passes Trusted Tester ID [12.B / WCAG standard 2.4.2: page-title-purpose](https://section508coordinators.github.io/TrustedTester/titles.html) passes.
The impact on users is browser tabs with multiple portal pages can be differentiated without having to open the tab to check the content. This is also beneficial to users of assitive technology when navigating between browser tabs.
Related PR explaining Next JS implementation for custom page titles across the system: [ feat: a11y: assigns unique page titles to each page in the portal #1037](https://github.com/USSF-ORBIT/ussf-portal-client/issues/1037)
on other pages, I notice a bunch …
=> fix: adds page title to Guardian Directory page

src/components/AnnouncementInfo/AnnouncementInfo.test.tsx, src/components/AnnouncementInfo/AnnouncementInfo.tsx, src/helpers/openDocumentLink.test.ts, src/helpers/openDocumentLink.ts, src/pages/landing/[landingPage]/index.tsx, src/pages/ussf-documentation.tsx
* Refactors how we handle and open documents in the browser
* Instead of checking if a file is a pdf, this PR gets the extension and checks against a list of supported mime types. 
* If the extension is listed, it sets the correct mime type. This allows image files such as webp, png, jpg to be opened in the browser.
* If the extension is not listed, it defaults to `application/octet-stream`.
* If the extension cannot be opened in the browser, it automatically downloads to the user's local machine.
Test different file types anywhere we can display documents and make sure functionality works as expected. Images and pdfs should open in the browser, other files should download.
```sh
yarn dev
yarn dev
```
```sh …
```
=> feat: Support additional file types for opening docs in browser

src/layout/DefaultLayout/DefaultLayout.test.tsx, src/layout/DefaultLayout/DefaultLayout.tsx
this branch edits the `DefaultLayout.tsx` file which is out base for our core functionality pages`My Space`, `Sites & Applications`, `Guardian Directory` that have the left side nave and repeated `PageHeader` component to move the id anchor link for the `Skip to main content` link to direct to. 
This ensures the user can skip right to the unique page content instead of getting directed to the search, side nav, etc. 
This ensures compliance for WCAG 2.0  2.4.1 Bypass success criteria [Trusted Tester ID 9A](https://section508coordinators.github.io/TrustedTester/repetitive.html)
this PR does not make changes to the other page layouts, which appear to be compliant. I am unsure if we should skip the `Page Header` component on the `PageLayout.tsx` layout.
```sh
yarn dev
cd …
```
=> fix: a11y: move skip link anchor entry point to unique page content in default layout

src/helpers/openDocumentLink.test.ts, src/helpers/openDocumentLink.ts
* Fixes extension parsing to work with urls that both end with the extension, and end with additional params (added by s3, in this case).
* Updates tests
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> fix: Update code to account for params on end of asset url in s3

.github/workflows/node-ci.yml, package.json
Change "test" -> "test:unit" for the Gitlab migration.
Not sure how this will interact with existing pipelines, so this PR is only for testing and should not be merged without scrutiny.
=> chore: Change test to test:unit for the Gitlab migration

src/__tests__/pages/_error.test.tsx, src/__tests__/pages/login-notice.test.tsx, src/__tests__/pages/update-browser.test.tsx, src/components/AnnouncementDate/AnnouncementDate.test.tsx, src/components/ArticleDateIcon/ArticleDateIcon.test.tsx, src/components/ArticleList/ArticleList.test.tsx, src/components/ArticleListItem/ArticleListItem.test.tsx, src/components/BreadcrumbNav/BreadcrumbNav.test.tsx, src/components/Collection/Collection.test.tsx, src/components/CustomCollection/CustomCollection.test.tsx, src/components/CustomCollection/EditableCollectionTitle.test.tsx, src/components/CustomCollection/RemovableBookmark.test.tsx, src/components/DropdownMenu/DropdownMenu.test.tsx, src/components/EPubsCard/EPubsCard.test.tsx, src/components/FeedbackCard/FeedbackCard.test.tsx, src/components/Footer/Footer.test.tsx, src/components/Loader/Loader.test.tsx, src/components/Logo/Logo.test.tsx, src/components/NewsCarousel/NewsCarousel.test.tsx, src/components/PageHeader/PageHeader.test.tsx, src/components/SearchBanner/SearchBanner.test.tsx, src/components/SelectableCollection/SelectableCollection.test.tsx, src/components/Tag/Tag.test.tsx, src/components/Widget/Widget.test.tsx, src/components/util/Flash/Flash.test.tsx, src/components/util/ModalPortal.test.tsx, src/components/util/NavLink/NavLink.test.tsx
All engineers previously agreed to use the `test` prefix as opposed to `it` for all unit tests. We have been updating each file as we touch it, but now that we are handing the project off, this PR changes all remaining tests to follow the previously established convention.
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> chore: Change all remaining it to test
