USSF-ORBIT/ussf-portal-client

.github/dependabot.yml
Adds a `dependabot.yml`. Should update `docker` and `npm` both in the root directory and should update `npm` in the `cypress` directory. (I'm not sure if this path is correct, but I need the file to exist to test it.
Fixes #69
=> ci: Initial commit for Dependabot configuration

.github/workflows/storybook-branch.yml, next.config.js
This PR adds branch deploys of the prototype (beta) to Netlify.
* To trigger a branch deploy, open a PR and add the label `prototype`.
Fixes #221 
One note: The branch url posted won't be live until the deploy is complete, so you may get a not found error if you click too quickly after triggering the deploy.
=> ci: Add prototype branch deploys

src/components/Bookmark/Bookmark.module.scss, src/components/CustomCollection/CustomCollection.module.scss, src/components/CustomCollection/CustomCollection.tsx, src/components/Header/Header.module.scss, src/components/Search/Search.module.scss, src/styles/pages/sitesAndApplications.module.scss
Fixes [#286](https://github.com/USSF-ORBIT/ussf-portal-client/issues/286)
- Add hover states to bookmark/link button
- Added hover over to "add link" button
- Added hover over to main navigation links
- Changes "Search" text to Trebuchet
- Added button styles on alphabetical/type sorts
=> [WIP] Sites & Applications UX fixes (Mal)

package.json, src/components/AddWidget/AddWidget.module.scss, src/components/Bookmark/Bookmark.module.scss, src/components/Collection/Collection.module.scss, src/components/Collection/Collection.stories.tsx, src/components/CustomCollection/CustomCollection.module.scss, src/components/CustomCollection/CustomCollection.stories.tsx, src/components/CustomCollection/CustomCollection.tsx, src/components/Footer/Footer.module.scss, src/components/Header/Header.module.scss, src/components/MySpace/MySpace.module.scss, src/components/MySpace/MySpace.tsx, src/components/Search/Search.module.scss, src/components/SelectableCollection/SelectableCollection.stories.tsx, src/layout/Beta/DefaultLayout/DefaultLayout.module.scss, src/layout/Beta/DefaultLayout/DefaultLayout.tsx, src/pages/beta/sites-and-applications.tsx, src/stories/Typography.module.scss, src/styles/pages/sitesAndApplications.module.scss, yarn.lock
This PR makes some small UX/design fixes as described in #286 (everything listed in the **COMPLETED** section). It does _not_ cover the items contained in separate issues.
Fixes #286 
Review the deployed app & Storybook against the list of UX fixes above and verify that they are in fact completed.
=> feat: Sites & Applications UX fixes

.github/workflows/dev-aws-ecr.yml, .github/workflows/prototype-aws-ecr.yml
I suck at copy and paste...that continues to be true.
=> ci: fixing collision in github actions

CHANGELOG.md, package.json
* Add custom link modal ([#250](https://github.com/USSF-ORBIT/ussf-portal-client/issues/250)) ([8dfc7af](https://github.com/USSF-ORBIT/ussf-portal-client/commit/8dfc7af261f54bfdd4b872ce1c71c644e31d6fa7))
* Add custom link to collection ([#249](https://github.com/USSF-ORBIT/ussf-portal-client/issues/249)) ([95bc376](https://github.com/USSF-ORBIT/ussf-portal-client/commit/95bc376b5fecc68891d504ec7db432df4b3e65ab))
* Add existing collections to My Space ([#255](https://github.com/USSF-ORBIT/ussf-portal-client/issues/255)) ([bb94c73](https://github.com/USSF-ORBIT/ussf-portal-client/commit/bb94c73459d05a8d58039dba3f21b067a62424f0))
* Add links to collections from alphabetically-sorted Sites & Applications page ([#278](https://github.com/USSF-ORBIT/ussf-portal-client/issues/278)) …
=> chore(release): 2.0.0-alpha.0

.github/workflows/dev-aws-ecr.yml, .github/workflows/prototype-aws-ecr.yml
I changed the name of the step, but I didn't update the subsequent step that used it's output. This fixes that.
=> ci: Give actions the right output, it might work

.github/CODEOWNERS
=> chore: Remove Noah and Mallory from CODEOWNERS

public/assets/images/USSF_Vertical_Gradient_RGBicononly-01.svg, src/__tests__/pages/404.test.tsx, src/__tests__/pages/500.test.tsx, src/components/Logo/Logo.stories.tsx, src/components/Logo/Logo.tsx, src/components/MVP/Header/Header.module.scss, src/layout/Beta/ErrorLayout/ErrorLayout.module.scss, src/layout/Beta/ErrorLayout/ErrorLayout.tsx, src/pages/404.tsx, src/pages/500.tsx
This PR implements custom 404 & 500 pages in the portal app. It also performs an auth check on the 404 page and redirects the user to log in if they aren't (we may want to revisit this requirement when we redesign the Login page).
I also left-aligned the "Join beta" button on the MVP site per @MKDale 's request!
Fixes #431 
Fixes #432 
You can view these pages locally by going to:
- http://localhost:3000/500
- http://localhost:3000/404
Or on the AWS environment:
- https://dev.ussforbit.us/404
- https://dev.ussforbit.us/500
=> feat: Custom error pages, Join beta button alignment

src/__tests__/pages/home/index.test.tsx, src/components/MVP/AnnouncementCard/AnnouncementCard.module.scss, src/components/MVP/AnnouncementCard/AnnouncementCard.tsx, src/components/MVP/Header/Header.module.scss, src/components/MVP/Header/Header.tsx, src/layout/MVP/DefaultLayout/DefaultLayout.module.scss, src/pages/index.tsx
This PR makes several changes to solve for the Join Beta button not being visible at certain screen sizes:
- For mobile (narrow), the button has been moved into the navigation menu
- For short desktop windows, the sidebar navigation can be scrolled down
- Additionally, the insignia announcement on the MVP home page has been replaced with an announcement about the beta
Fixes #456
=> fix: Join Beta button not visible at certain window sizes

src/models/Bookmark.test.ts, src/models/Bookmark.ts, src/models/Collection.test.ts, src/models/Collection.ts, src/resolvers/index.ts, src/types/index.ts
Continues refactoring work from #472 and cleans up a bit more.
* Standardizes error logging and handling in BookmarkModel and CollectionModel
* Adds types/consistent function signatures like introduced in #472
* Updates tests
Fixes #472
=> dev: Add consistency in models for error handling, function signatures

.github/workflows/dev-aws-ecr.yml
Commit https://github.com/USSF-ORBIT/ussf-portal-client/commit/23cc2c9cb8aee06bf8113b9efdebd7c5ac831ac5#diff-020de644d3a83b82b42925baa8802016fd9c1bdb2f44dc2e1e7c2b6bea61542a altered the YAML formatting in our automated AWS dev workflow file, causing it to be invalid. This PR fixes that.
=> ci: Fix YAML formatting error in AWS auto deploy workflow

e2e/cypress/database/seedMongo.js, e2e/cypress/integration/sites-and-applications.spec.js, src/__tests__/pages/beta/index.test.tsx, src/components/CustomCollection/CustomCollection.module.scss, src/components/CustomCollection/CustomCollection.test.tsx, src/components/CustomCollection/CustomCollection.tsx, src/components/CustomCollection/EditableCollectionTitle.test.tsx, src/components/CustomCollection/EditableCollectionTitle.tsx, src/components/MySpace/MySpace.test.tsx, src/components/MySpace/MySpace.tsx, src/styles/_settings.scss
=> feat: Edit collection title ux improvements

.github/workflows/storybook-deploy.yml
Fixes Storybook GH pages deploy based on [this thread](https://github.com/storybookjs/storybook-deployer/issues/77)
=> chore(ci): Fix storybook deploy token

src/components/PersonalData/PersonalData.test.tsx, src/components/PersonalData/PersonalData.tsx
* Removes hardcoded links in the Personal Data component
* Updates tests
---
Run locally and verify that the personal data links have been removed on the beta homepage.
`yarn services:up`
`yarn dev`
---
---
=> feat: Remove hardcoded personal info links

.github/pull_request_template.md
Added the test script link and checkboxes for the user testing to the PR template.
=> docs: Adding test script walkthrough to the PR template

src/components/CustomCollection/CustomCollection.module.scss
- Updates style for the "Undo remove" button to match that of the Bookmark component
---
---
- ... 
- Run through the [Test Script](hhttps://docs.google.com/spreadsheets/d/1eV8UK0aJZ0qrzjnXf5SJ_uRiV7bpsj3yrhRFEkjOvV4/edit?usp=sharing):
---
=> feat: Update undo button style

scripts/add-rds-cas.sh
https://docs.aws.amazon.com/documentdb/latest/developerguide/ca_cert_rotation_pdt.html
=> chore: adding us-gov-west-1 ca bundle

.github/workflows/dev-aws-ecr.yml, .github/workflows/man-dev-aws-ecr.yml, .github/workflows/man-dev-c1.yml
Much like the other [PR](https://github.com/USSF-ORBIT/ussf-portal-cms/pull/45), this fixes a typo, updates some names for consistency and creates a manual C1 job, just in case.
=> ci: consistency in job names and manual c1 job

src/components/CustomCollection/CustomCollection.test.tsx, src/components/CustomCollection/CustomCollection.tsx, src/components/CustomCollection/RemovableBookmark.tsx, src/lib/keystoneClient.ts
- Retrieve bookmark URLs and labels from CMS instead of Mongo to make sure they are kept up to date
Log in as `cmsadmin / cmsadminpass` and:
- In the Keystone UI, edit the URL (or label) of an existing bookmark that is in one of the user's collections.
- Navigate to the user's My Space, refresh the page and verify that you see the change that was made in Keystone.
Be sure to have the latest version of the CMS on your local machine and running.
---
=> refactor: Sync all canonical url updates

.github/workflows/build-push-c1-art.yml, .github/workflows/dev-aws-ecr.yml, .github/workflows/man-dev-aws-ecr.yml, .github/workflows/man-dev-c1.yml
- remove docker build commands
- add buildx action to run docker build
- Metadata action to pull image labels
- For ECR, docker/setup-buildx-action is now pushing.
---
- For the c1 builds, we are still using docker push command instead of the docker/setup-buildx-action due to an auth issue.
---
- ... 
- Run through the [Test Script](hhttps://docs.google.com/spreadsheets/d/1eV8UK0aJZ0qrzjnXf5SJ_uRiV7bpsj3yrhR …
=> ci: Adding buildx to github actions for docker build

.github/CODEOWNERS
=> chore: removing Suz from codeowners

CHANGELOG.md, package.json
* Announcement carousel ([#669](https://github.com/USSF-ORBIT/ussf-portal-client/issues/669)) ([2b52c0e](https://github.com/USSF-ORBIT/ussf-portal-client/commit/2b52c0e0ea3bed60f37f60c95bd4a7471dcce8ef))
* ePubs search ([#693](https://github.com/USSF-ORBIT/ussf-portal-client/issues/693)) ([1c6725d](https://github.com/USSF-ORBIT/ussf-portal-client/commit/1c6725d6c944ebfc228f0b25e6f2ce25e9e25fdd))
* update the branch pattern and link to Shortcut ([#689](https://github.com/USSF-ORBIT/ussf-portal-client/issues/689)) ([87961af](https://github.com/USSF-ORBIT/ussf-portal-client/commit/87961af152e4d73d484707412692994bbbae1136))
=> chore(release): 4.4.0

CHANGELOG.md, package.json
* Add link to ORBIT Blog on portal ([#719](https://github.com/USSF-ORBIT/ussf-portal-client/issues/719)) ([7ce6af9](https://github.com/USSF-ORBIT/ussf-portal-client/commit/7ce6af9e3ca4b06dbe707f657b68ff58ae8ef664))
* Create internal news page and update existing external news page ([#711](https://github.com/USSF-ORBIT/ussf-portal-client/issues/711)) ([feadcae](https://github.com/USSF-ORBIT/ussf-portal-client/commit/feadcae197d16079a49c7304c97d88ba6eb4d638))
* Edit display name ([#706](https://github.com/USSF-ORBIT/ussf-portal-client/issues/706)) ([372ad2a](https://github.com/USSF-ORBIT/ussf-portal-client/commit/372ad2a3d3daa0963d691d33fc0322516c79132e))
* Pagination component ([#690](https://github.com/USSF-ORBIT/ussf-portal-client/issues/690)) …
=> chore(release): 4.5.0

.github/workflows/semantic-pr.yml, package.json
In our release notes, we're not capturing security fixes, and we should. This is an attempt to do so. The commit message for this PR is the test.
=> security: adding security type. this commit is also a test

CHANGELOG.md, package.json
* Add Light / Dark mode toggle to the portal ([#766](https://github.com/USSF-ORBIT/ussf-portal-client/issues/766)) ([e37be05](https://github.com/USSF-ORBIT/ussf-portal-client/commit/e37be0552cf9ad1dbeb84c1679e41e94b62fa636))
* add mutation for get and set theme ([#774](https://github.com/USSF-ORBIT/ussf-portal-client/issues/774)) ([8141b36](https://github.com/USSF-ORBIT/ussf-portal-client/commit/8141b3626fb0e98aafeb60f17a9ac37f078d3732))
* Move Add Custom Link to ComboBox ([#754](https://github.com/USSF-ORBIT/ussf-portal-client/issues/754)) ([d35fa74](https://github.com/USSF-ORBIT/ussf-portal-client/commit/d35fa740625fdd1d943bdee76fc76a8930d3128e))
* update user model for saving dark mode ([#772](https://github.com/USSF-ORBIT/ussf-portal-client/issues/772)) …
=> chore(release): 4.8.0

Dockerfile
- remove a harmless but unnecessary trailing double quote from Dockerfile
---
=> fix: remove unnecessary trailing double quote

package.json, yarn.lock
- Updates `@graphql-codegen/cli` dev dependency
---
See [https://github.com/USSF-ORBIT/ussf-portal-client/security/dependabot/34](url)
---
- ... 
- Run through the [Test Script](hhttps://docs.google.com/spreadsheets/d/1eV8UK0aJZ0qrzjnXf5SJ_uRiV7bpsj3yrhRFEkjOvV4/edit?usp=sharing):
---
=> chore: @graphql-codegen/cli update

package.json, yarn.lock
Sadly, I don't think my prior PR fixed this, so I think this will https://github.com/USSF-ORBIT/ussf-portal-client/security/dependabot/51
=> chore: pinning xmldom at 0.8.3

CHANGELOG.md, package.json
* a11y: enhances focus styling in bookmarks and configures consistent focus styling  ([#815](https://github.com/USSF-ORBIT/ussf-portal-client/issues/815)) ([fd542f8](https://github.com/USSF-ORBIT/ussf-portal-client/commit/fd542f8b96c22463484e5d8e972c128581a161a5))
* adjusts button styling to be in alignment with Figma button styling ([#818](https://github.com/USSF-ORBIT/ussf-portal-client/issues/818)) ([e8de88d](https://github.com/USSF-ORBIT/ussf-portal-client/commit/e8de88d8834e43ccc8996d113757f2225c2974cd))
* design: secondary buttons colors / more button design updates  ([#830](https://github.com/USSF-ORBIT/ussf-portal-client/issues/830)) ([2e6c0ac](https://github.com/USSF-ORBIT/ussf-portal-client/commit/2e6c0acbe45d10a07758ff24686651c554c12639))
* Light/Dark theme settings are …
=> chore(release): 4.9.1

CHANGELOG.md, package.json
* Enable dark mode toggle ([#859](https://github.com/USSF-ORBIT/ussf-portal-client/issues/859)) ([a3a02a1](https://github.com/USSF-ORBIT/ussf-portal-client/commit/a3a02a16dbb3726494fd4d6a4d9a0bc6c66a9b50))
* **deps:** update dependency apollo-server-core to v3.11.0 [security] ([#845](https://github.com/USSF-ORBIT/ussf-portal-client/issues/845)) ([e735f78](https://github.com/USSF-ORBIT/ussf-portal-client/commit/e735f78b806c533845a99957f11ef7856855f3d4))
* design: dark mode improvements ([#844](https://github.com/USSF-ORBIT/ussf-portal-client/issues/844)) ([8f0fd1d](https://github.com/USSF-ORBIT/ussf-portal-client/commit/8f0fd1dccb39567e8af6f8ca346eeae2a8a49185))
=> chore(release): 4.10.0

.github/workflows/storybook-deploy.yml
I had a syntax issue here causing the storybook action to fail and not deploy. This should fix it.
=> ci: fixing storybook action

CHANGELOG.md, package.json
* Create USSF Documentation page ([#860](https://github.com/USSF-ORBIT/ussf-portal-client/issues/860)) ([6c5d6b3](https://github.com/USSF-ORBIT/ussf-portal-client/commit/6c5d6b34cde9c6e1fd6d26c1d8bdb7acae03df41))
* UI modifications to the article template ([#856](https://github.com/USSF-ORBIT/ussf-portal-client/issues/856)) ([dc7402c](https://github.com/USSF-ORBIT/ussf-portal-client/commit/dc7402c6a0f4366ae4b758d97330e684f7452e18))
=> chore(release): 4.11.0

CHANGELOG.md, package.json
* Add support for hero image in articles ([#862](https://github.com/USSF-ORBIT/ussf-portal-client/issues/862)) ([56721db](https://github.com/USSF-ORBIT/ussf-portal-client/commit/56721dbff4bfd6562ac40464d3b16330c8807df1))
* add USSF Guardian Commitment Poster to docs page ([#888](https://github.com/USSF-ORBIT/ussf-portal-client/issues/888)) ([07fb472](https://github.com/USSF-ORBIT/ussf-portal-client/commit/07fb47231ba570386ed6835300ac92a14c8ecdc1))
* Create USSF Documentation page ([#860](https://github.com/USSF-ORBIT/ussf-portal-client/issues/860)) ([6c5d6b3](https://github.com/USSF-ORBIT/ussf-portal-client/commit/6c5d6b34cde9c6e1fd6d26c1d8bdb7acae03df41))
* Display hero image in article layout ([#884](https://github.com/USSF-ORBIT/ussf-portal-client/issues/884)) …
=> chore(release): 4.12.0

CHANGELOG.md, package.json
* add mock user for ThemeToggle story ([#889](https://github.com/USSF-ORBIT/ussf-portal-client/issues/889)) ([5961890](https://github.com/USSF-ORBIT/ussf-portal-client/commit/59618903d2e65c12d1a61cceb8f963abcdb2cfbb))
* design: adds icons into theme toggle ([#895](https://github.com/USSF-ORBIT/ussf-portal-client/issues/895)) ([f72da84](https://github.com/USSF-ORBIT/ussf-portal-client/commit/f72da84642bc22ea861b36d2a3d7416c22a08478))
* design: updates page loader animation ([#886](https://github.com/USSF-ORBIT/ussf-portal-client/issues/886)) ([6f7472e](https://github.com/USSF-ORBIT/ussf-portal-client/commit/6f7472e7d68b7672a69fd3349b5d4d8abb2fa4de))
* **deps:** Upgrade node 18 ([#881](https://github.com/USSF-ORBIT/ussf-portal-client/issues/881)) …
=> chore(release): 4.12.1

scripts/add-dod-cas.sh
- DoD Cyber Exchange has released a new Root CAs Bundle. This has replaced the, likely, expired bundle that we have been using, of which we no longer have access to download. The Certs allow us to connect to Artifactory.
---
---
- ... 
- Run through the [Test Script](hhttps://docs.google.com/spreadsheets/d/1eV8UK0aJZ0qrzjnXf5SJ_uRiV7bpsj3yrhRFEkjOvV4/edit?usp=sharing):
---
=> chore: update DoD Root CAs Bundle

.github/settings.yml, .happo.js
To ensure our app works in multiple browsers we are enabling happo to do visual regression testing in the top 3 browsers we support namely chrome, edge, and firefox. The latter two are new from before.
Also updated github settings to ensure that PR title is used when merging to main.
Look at happo build should test cross browser, though I'm not sure if that only shows after this is merged or not.
---
- ...  …
=> chore: enable firefox and edge in happo tests

src/__fixtures__/operations/getUser.ts, src/components/PageHeader/PageHeader.stories.tsx, src/components/PersonalData/PersonalData.stories.tsx, src/components/PersonalData/PersonalData.test.tsx, src/components/PersonalData/PersonalData.tsx, src/layout/DefaultLayout/DefaultLayout.test.tsx, src/layout/DefaultLayout/DefaultLayout.tsx, src/operations/portal/queries/getUser.graphql, yarn.lock
Adds getUser query to address duplicate user creation bug
---
- Go to `localhost:8888` and delete your local Mongo dev db. Return to the app and login with any user. This should cause the db to be recreated with a new user.
- Check the db and make sure that there is only one user. Login with as many users as you want and verify that no duplicates are being created.
Note: I added the `getUser` query to the `DefaultLayout` component so we're getting the user's theme there as well. I attempted to pass that value down via props, but couldn't get it working properly. It basically reintroduces the theme bug that we had before, where the theme is not persisted as the user navigates through the app. I'm going to write a story for our tech liability backlog to work on at a later date.
In the CMS …
=> fix: Duplicate user bug

CHANGELOG.md, package.json
* Featured Shortcuts component ([#956](https://github.com/USSF-ORBIT/ussf-portal-client/issues/956)) ([73258c1](https://github.com/USSF-ORBIT/ussf-portal-client/commit/73258c10299c361a8faf8d98e987841a87db15da))
* Guardian Ideal event tracking ([#944](https://github.com/USSF-ORBIT/ussf-portal-client/issues/944)) ([02afe2d](https://github.com/USSF-ORBIT/ussf-portal-client/commit/02afe2ddbc5f0049ed938f5c9b6ca9862783c352))
* Duplicate user bug ([#958](https://github.com/USSF-ORBIT/ussf-portal-client/issues/958)) ([d3be39b](https://github.com/USSF-ORBIT/ussf-portal-client/commit/d3be39b1d827a3430d2505863ec62ad2d429d253))
=> chore(release): 4.17.0

src/styles/pages/sitesAndApplications.module.scss
- Makes the toolbar on the Sites & Apps page sticky so that it follows the users scroll
---
Run the app locally: 
- Navigate to `/sites-and-applications`
- Click 'Select multiple collections'
- Scroll down and verify that the toolbar follows your scroll
In the CMS: `yarn services:up && yarn dev`
In the portal client: `yarn dev`
---
- ... 
- Run through the [Test …
=> feat: Sticky container bar for Add Selected

CHANGELOG.md, package.json
* design: storybook: adds featured shortcuts to storybook and styles for dark mode ([#960](https://github.com/USSF-ORBIT/ussf-portal-client/issues/960)) ([4e47dcf](https://github.com/USSF-ORBIT/ussf-portal-client/commit/4e47dcf0215994ce265b7b4165782dfe743f0947))
* Sticky container bar for Add Selected ([#969](https://github.com/USSF-ORBIT/ussf-portal-client/issues/969)) ([d1c8428](https://github.com/USSF-ORBIT/ussf-portal-client/commit/d1c8428f7a629c21cbfb9217745beda9329a87d4))
* design: storybook: link color adjustments and storybook documentation ([#967](https://github.com/USSF-ORBIT/ussf-portal-client/issues/967)) ([79f3b5f](https://github.com/USSF-ORBIT/ussf-portal-client/commit/79f3b5f8b1afcd5969a354ebe92688644ac77af9))
* Remove any null bookmarks and prevent future ones …
=> chore(release): 4.18.0

.github/PULL_REQUEST_TEMPLATE/release.md, .github/pull_request_template.md
Applying the changes to the template that we discussed. The PR https://github.com/USSF-ORBIT/ussf-portal/pull/261 adds more detailed documentation on the template usage.
Let me know if I missed anything, have any typos, or if there is some better way to lay this out.
=> docs: update pr templates

.github/workflows/build-push-c1-art.yml
- Tag Docker image for Artifactory Test and Prod repositories and push
---
For how the job runs, see Workflow Run: https://github.com/USSF-ORBIT/ussf-portal-cms/actions/runs/5018160502/jobs/8997220007
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> build: automate image copy from artifactory dev to test and prod

.github/workflows/build-docker-cache-artifacts.yml
- add a workflow that:
- builds the docker image and exports the docker build cache to a directory
- uploads the docker build cache and image manifest to GHA Artifacts
- saves the docker build cache to GHA cache with the image digest as key
---
See this workflow summary: https://github.com/USSF-ORBIT/ussf-portal-client/actions/runs/4886817479
to see what the artifact looks like.
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> build: save Docker build cache in GH Artifacts and GHA cache

Dockerfile
- Ahead of Debian 12's 6/10/2023 [release date](https://lists.debian.org/debian-devel-announce/2023/04/msg00007.html), we should pin our images to Debian 11 so that our builds do not break.
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> chore: pin debian 11 docker image tags

.storybook/preview.tsx
We want Happo to do regression testing for light and dark mode. Currently it only takes snapshots of our components in light mode. This PR updates the configuration to take snapshots of both themes.
Check out the happo diffs in the build. There will be many renamed to include `light` in the title and about the same number for dark mode under added.
---
---
=> build: happo tests dark mode

src/stories/type.stories.tsx, src/styles/sfds/index.scss
Changed h3 from book weight to bold weight.
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> feat: Change h3 from book weight to bold weight

docs/development.md
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> docs: Update Matomo port in development.md

Dockerfile
---
- Upgrade Debian 11 "Bullseye" Docker Images to Debian 12 "Bookworm"
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> build: upgrade docker images to bookworm

.envrc, docker-compose.services.yml
- It appears Mongo Express has added default credentials to their container, but as we only use this in Dev we prefer to keep the credentials blank. This PR sets the Environment Variables for the Mongo Express server's credentials to be blank via `.envrc` and imports them into the container
---
Run a `direnv allow` after changing the `.envrc`.
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> chore: set mongo express creds to blank

scripts/add-dod-cas.sh
- Change static file/directory names to have wildcards in the `add-dod-cas.sh` shell script so that minor version updates to the DoD PKI Certificate package will not break the file and directory names in the script.
- Moved the working directory of much of the script logic back one level for easier maintenance of script
- 
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> build: allow all minor version updates of pkcs v5_*

src/stores/authContext.test.tsx, src/stores/authContext.tsx
Fix the redirect for articles, landing pages and search queries
---
Before testing, make sure that you have articles in your local CMS that are published.
Open an incognito browser (or clear your cookies) and enter `http://localhost:3000/articles/<slug for the article>`
- You should be redirected to the login page and the url should be `http://localhost:3000/login?redirectTo=/articles/<slug for the article>`
- Finish logging in and you should then be taken to the article
There are a couple of other ways to test this if you want:
- While unauthenticated, try to navigate directly to a landing page. The url when on the login page should be `http://localhost:3000/login?redirectTo=/landing/<name of landing page>`
- While unauthenticated, try to go to a search result. Ex: …
=> fix: Redirect bug

.mergify.yml
=> chore: Add the logic to make mergify consistent across accounts

.github/settings.yml, .mergify.yml
Make the e2e tests required again
=> chore: Add e2e tests back in

src/pages/api/thirdparty/resolvers.ts
Main has a lint warning that is blocking the build. This PR fixes it.
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> dev: fix lint warning

package.json, src/components/Search/Search.module.scss, src/components/Search/Search.test.tsx, src/components/Search/Search.tsx, yarn.lock
- Upgrade @trussworks/react-uswds to latest version
- Remove `disabled` prop and language surrounding the beta
---
The main goal of this upgrade is to address an accessibility violation that we found in the `Search` component that is exported from the react-uswds library. It would be good to test with ANDI if you can.
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> build: Update @trussworks/react-uswds to latest version

src/pages/news-announcements.tsx, src/pages/news.tsx
- Fixes typo on `/news` and `/news-announcements`
---
```sh
yarn dev
yarn dev
```
```sh
yarn storybook
```
---
---
=> fix: Typo on News page
